name: Release Binaries

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Install GLib development libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y libglib2.0-dev pkg-config

      - name: Build
        run: make

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            bin/gshortcuts-linux-amd64
